# Generated by Django 2.2.5 on 2019-10-30 22:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mystorage', '0002_album_filse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Filse',
            new_name='Files',
        ),
    ]
